### ISSUE TITLE
Provision dialog for ec2 with public images fails - high worker memory utilization

### ISSUE THREAD

**Issue by dmetzger57** [ManageIQ/manageiq-automation_engine#446]
Original BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1662972

Steps to Reproduce:
1. Add ec2 provider with region us-east-1 and public images enabled 
2. Wait for full refresh
3. Go to Compute -> Cloud -> Instances
4. Select provision an instance
5. Select an image and go to next step

Actual results:
When I select an image and then click on continue I get Error requesting data from server

**Comment by Fryguy** [comment]
@NickLaMuro Seems you were working on this in the BZ...is it still in your court or should it be moved to someone else or marked help wanted?

**Comment by NickLaMuro** [comment]
@Fryguy A year and a half ago, I had provided some fixes and approaches on how to improve this, but it was deemed low priority so they never got priority for review or pressured (from management) to be pursued further.

I have no problem taking this ticket on, but progress on addressing what I already have:

- https://github.com/ManageIQ/manageiq/pull/18353  (already merged)
- https://github.com/ManageIQ/manageiq-schema/pull/322
- https://github.com/ManageIQ/manageiq/pull/18354

has been slow or non-existent.  Comments like this one:

https://github.com/ManageIQ/manageiq-schema/pull/322#issuecomment-561756398

Remained unanswered, which gave me the impression that this was not a heavily desired improvement, and so I haven't pursued it further.  I think we the remaining PRs, there is a big discussion to be had about if the approach of adding a caching column is the right approach and one we want to move forward with, or if it will potentially cause bugs itself and isn't worth the risk.

Also worth noting, we probably have had 3 releases since I originally opened these proposals, so I probably have to re-evaluate my performance improvements as well with the updated codebase.

**Comment by Fryguy** [comment]
No need to prioritize now. This just came in and I didn't know that the status was.  Thanks for the updates
