### ISSUE TITLE
[bug] Git import imports all available domains, but locks only one of them

### ISSUE THREAD

**Issue by paulslaby** [ManageIQ/manageiq-automation_engine#45]
When I import from git repo with two domains, both of them get imported (not nice, but acceptable when documented). But only one of them is refreshable (assigned git repository) and locked. 

When refreshing a domain, it works as expected - only that one domain is refreshed. It would be great to work in the same way when importing...

**Comment by gmcculloug** [comment]
@mkanoor Can you review this issue and provide feedback?  Thinking this is something @pkomanek could work on.

**Comment by mkanoor** [comment]
@paulslaby @gmcculloug 
Typically our recommendation has been 1 domain per git repository.
I think in your case you have 2 domains in your repository.
Since the underlying code searches for multiple domain, when it encounters them it imports it in.
We can restrict the git importer to only import a single domain and reject if the domain has multiples.
@pkomanek can you please add a check to restrict git importer to a single domain.

**Comment by paulslaby** [comment]
Thanks for reaction. Sounds like a good pattern. I'm going to redesign my use case.
I hope, you'll make it behave more expected. But I understand, it's not priority.

**Comment by CCoupel** [comment]
Hi, i need to give my intention on this behaviour.
My customer manage its appliance with more than 3 domains in a single GIT repo.
It will be usefull if, as for file import, we can choose which domain we want to use instead of rejecting all unless we will not import all the domains. This way, we have a coherent working maner on importing from file and importing from GIT.

**Comment by JPrause** [comment]
@paulslaby is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by paulslaby** [comment]
Probably the problem in the code is still valid, but it is not pain for me any more, because I followed the mkanoor's advice to have only 1 domain per repository.

**Comment by gmcculloug** [comment]
Note: multi-domain import is now prevented.  See https://github.com/ManageIQ/manageiq-automation_engine/pull/124
